option(
  'avisynth',
  type: 'boolean',
  value: false,
  description: 'Enable avisynth',
)
option(
  'test',
  type: 'boolean',
  value: false,
  description: 'Enable test',
)
option(
  'wheel',
  type: 'boolean',
  value: false,
  description: 'Enable Python plugin',
)
option(
  'sdist',
  type: 'boolean',
  value: false,
  description: 'Configure only enough targets to build a source distribution',
)
